version: '3.3'
services:

  db:
#   image: postgres
    build: ./db
    container_name: postgres
    environment:
       POSTGRES_PASSWORD: password
       POSTGRES_USER: postgres
       POSTGRES_DB: hibernateTutorials
    volumes:
       - ./pgdata:/var/lib/postgresql/data
    ports:
       - "5432:5432"

  web:
#   image: ecart
    build: ./web
    container_name: ecart
    depends_on:
       - db
    ports:
       - "8080:8080"
